In [27]:
import pandas as pd
from sklearn.metrics import classification_report
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv('cardio_train.csv', sep=';')

In [3]:
df

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df = df.drop('id', axis=1)

In [6]:
df

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,17474,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
69995,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,20540,1,170,72.0,120,80,2,1,0,0,1,0

In [7]:
df['age'] = (df['age'] / 365).astype('int32')

In [8]:
df

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,50,2,168,62.0,110,80,1,1,0,0,1,0
1,55,1,156,85.0,140,90,3,1,0,0,1,1
2,51,1,165,64.0,130,70,3,1,0,0,0,1
3,48,2,169,82.0,150,100,1,1,0,0,1,1
4,47,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
69995,52,2,168,76.0,120,80,1,1,1,0,1,0
69996,61,1,158,126.0,140,90,2,2,0,0,1,1
69997,52,2,183,105.0,180,90,3,1,0,1,0,1
69998,61,1,163,72.0,135,80,1,2,0,0,0,1
69999,56,1,170,72.0,120,80,2,1,0,0,1,0

In [9]:
df['weight'] = df['weight'].astype('int32')

In [10]:
df

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,50,2,168,62,110,80,1,1,0,0,1,0
1,55,1,156,85,140,90,3,1,0,0,1,1
2,51,1,165,64,130,70,3,1,0,0,0,1
3,48,2,169,82,150,100,1,1,0,0,1,1
4,47,1,156,56,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
69995,52,2,168,76,120,80,1,1,1,0,1,0
69996,61,1,158,126,140,90,2,2,0,0,1,1
69997,52,2,183,105,180,90,3,1,0,1,0,1
69998,61,1,163,72,135,80,1,2,0,0,0,1
69999,56,1,170,72,120,80,2,1,0,0,1,0

In [11]:
df.isna().sum()

age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [13]:
scaler = MinMaxScaler()
columns_to_scale = ['age', 'height', 'weight', 'ap_hi', 'ap_lo']
df[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])

In [14]:
df

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0.600000,2,0.579487,0.273684,0.016079,0.013550,1,1,0,0,1,0
1,0.742857,1,0.517949,0.394737,0.017934,0.014453,3,1,0,0,1,1
2,0.628571,1,0.564103,0.284211,0.017316,0.012647,3,1,0,0,0,1
3,0.542857,2,0.584615,0.378947,0.018553,0.015357,1,1,0,0,1,1
4,0.514286,1,0.517949,0.242105,0.015461,0.011743,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
69995,0.657143,2,0.579487,0.347368,0.016698,0.013550,1,1,1,0,1,0
69996,0.914286,1,0.528205,0.610526,0.017934,0.014453,2,2,0,0,1,1
69997,0.657143,2,0.656410,0.500000,0.020408,0.014453,3,1,0,1,0,1
69998,0.914286,1,0.553846,0.326316,0.017625,0.013550,1,2,0,0,0,1
69999,0.771429,1,0.589744,0.326316,0.016698,0.013550,2,1,0,0,1,0

In [15]:
X = df.drop('cardio', axis=1)

In [16]:
y = df['cardio']

In [17]:
X

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active
0,0.600000,2,0.579487,0.273684,0.016079,0.013550,1,1,0,0,1
1,0.742857,1,0.517949,0.394737,0.017934,0.014453,3,1,0,0,1
2,0.628571,1,0.564103,0.284211,0.017316,0.012647,3,1,0,0,0
3,0.542857,2,0.584615,0.378947,0.018553,0.015357,1,1,0,0,1
4,0.514286,1,0.517949,0.242105,0.015461,0.011743,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
69995,0.657143,2,0.579487,0.347368,0.016698,0.013550,1,1,1,0,1
69996,0.914286,1,0.528205,0.610526,0.017934,0.014453,2,2,0,0,1
69997,0.657143,2,0.656410,0.500000,0.020408,0.014453,3,1,0,1,0
69998,0.914286,1,0.553846,0.326316,0.017625,0.013550,1,2,0,0,0
69999,0.771429,1,0.589744,0.326316,0.016698,0.013550,2,1,0,0,1

In [18]:
y

0        0
1        1
2        1
3        1
4        0
        ..
69995    0
69996    1
69997    1
69998    1
69999    0
Name: cardio, Length: 70000, dtype: int64

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2, shuffle=True, random_state=42)

In [ ]:
lr = LogisticRegression()

In [21]:
lr.fit(X_train, y_train)

LogisticRegression()

In [23]:
predictions = lr.predict(X_test)

In [ ]:
cr = classification_report(predictions, y_test)

print(cr)

              precision    recall  f1-score   support

           0       0.68      0.64      0.66      7381
           1       0.63      0.66      0.64      6619

    accuracy                           0.65     14000
   macro avg       0.65      0.65      0.65     14000
weighted avg       0.66      0.65      0.65     14000